<?php

use App\Models\Employee;
use App\Models\Job;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // factory(\App\Models\Employee::class, 10)->create();

        $employees = [
            [
                'code' => "18017",
                'first_name' => "Ann Maureen",
                'middle_name' => "S",
                'last_name' => "Ladimo",
                'suffix' => null,
                'gender' => "Female",
                'birthdate' => "1982-02-24",
                'mobile_number' => null,
                'telephone_number' => null,
                'email' => null,
                'address' => "Polomolok, South Cotabato",
                "job" => "Inventory Personnel",
            ],
            [
                'code' => "17011",
                'first_name' => "Benhur",
                'middle_name' => "Altavas",
                'last_name' => "Paulo",
                'suffix' => null,
                'gender' => "Male",
                'birthdate' => "1989-02-01",
                'mobile_number' => null,
                'telephone_number' => null,
                'email' => null,
                'address' => "Polomolok, South Cotabato",
                "job" => "Senior Software Developer",
            ],
            [
                'code' => "19018",
                'first_name' => "Erron",
                'middle_name' => "Cerdania",
                'last_name' => "Intila",
                'suffix' => null,
                'gender' => "Male",
                'birthdate' => "1996-08-19",
                'mobile_number' => "09567653221",
                'telephone_number' => null,
                'email' => null,
                'address' => "Polomolok, South Cotabato",
                "job" => "Junior Software Developer",
            ],
            [
                'code' => "18013",
                'first_name' => "Elmer",
                'middle_name' => "Dalagan",
                'last_name' => "Datuin",
                'suffix' => null,
                'gender' => "Male",
                'birthdate' => "1994-06-16",
                'mobile_number' => null,
                'telephone_number' => null,
                'email' => null,
                'address' => "Polomolok, South Cotabato",
                "job" => "Utility and Maintenance",
            ],
            [
                'code' => "17017",
                'first_name' => "Erwin",
                'middle_name' => "M",
                'last_name' => "Vicente",
                'suffix' => null,
                'gender' => "Male",
                'birthdate' => "1985-01-03",
                'mobile_number' => null,
                'telephone_number' => null,
                'email' => null,
                'address' => "Polomolok, South Cotabato",
                "job" => "Field Service Engineer",
            ],
            [
                'code' => "18015",
                'first_name' => "Eduardo",
                'middle_name' => "S",
                'last_name' => "Melendrez",
                'suffix' => null,
                'gender' => "Male",
                'birthdate' => "1990-08-12",
                'mobile_number' => null,
                'telephone_number' => null,
                'email' => null,
                'address' => "Polomolok, South Cotabato",
                "job" => "Field Service Technician",
            ],
            [
                'code' => "17004",
                'first_name' => "Ina Kristie",
                'middle_name' => "M",
                'last_name' => "Almocera",
                'suffix' => null,
                'gender' => "Female",
                'birthdate' => "1985-05-12",
                'mobile_number' => null,
                'telephone_number' => null,
                'email' => null,
                'address' => "Polomolok, South Cotabato",
                "job" => "Accounts Receivable Specialist",
            ],
            [
                'code' => "17012",
                'first_name' => "Ma. Louie",
                'middle_name' => "V",
                'last_name' => "Pilota",
                'suffix' => null,
                'gender' => "Female",
                'birthdate' => "1994-12-18",
                'mobile_number' => null,
                'telephone_number' => null,
                'email' => null,
                'address' => "Polomolok, South Cotabato",
                "job" => "Inventory, Warehouse, and Purchasing Officer",
            ],
            [
                'code' => "19030",
                'first_name' => "Nicho",
                'middle_name' => "G",
                'last_name' => "Bolivar",
                'suffix' => null,
                'gender' => "Male",
                'birthdate' => "1994-03-21",
                'mobile_number' => null,
                'telephone_number' => null,
                'email' => null,
                'address' => "Polomolok, South Cotabato",
                "job" => "Junior Sales & Marketing Representative",
            ],
            [
                'code' => "19032",
                'first_name' => "Paul Michael",
                'middle_name' => "R",
                'last_name' => "Cruz",
                'suffix' => null,
                'gender' => "Male",
                'birthdate' => "1995-10-27",
                'mobile_number' => null,
                'telephone_number' => null,
                'email' => null,
                'address' => "Polomolok, South Cotabato",
                "job" => "Stock Personnel",
            ],
            [
                'code' => "17009",
                'first_name' => "Remond",
                'middle_name' => "L",
                'last_name' => "Oro",
                'suffix' => null,
                'gender' => "Male",
                'birthdate' => "1990-08-30",
                'mobile_number' => null,
                'telephone_number' => null,
                'email' => null,
                'address' => "Polomolok, South Cotabato",
                "job" => "Operations Services and Logistics Officer",
            ],
            [
                'code' => "17018",
                'first_name' => "Romel",
                'middle_name' => "L",
                'last_name' => "Wael",
                'suffix' => null,
                'gender' => "Male",
                'birthdate' => "1990-09-21",
                'mobile_number' => null,
                'telephone_number' => null,
                'email' => null,
                'address' => "Polomolok, South Cotabato",
                "job" => "Logistics Coordinator",
            ],
            [
                'code' => "19034",
                'first_name' => "Vince",
                'middle_name' => "D",
                'last_name' => "Deberto",
                'suffix' => null,
                'gender' => "Male",
                'birthdate' => "1997-05-27",
                'mobile_number' => null,
                'telephone_number' => null,
                'email' => null,
                'address' => "Polomolok, South Cotabato",
                "job" => "Junior Technical Support",
            ],
        ];

        foreach ($employees as $key => $value) {
            $job = Job::where('name', $value["job"])->first();

            if (!is_null($job)) {
                Employee::create([
                    'code' => $value["code"],
                    'first_name' => $value["first_name"],
                    'middle_name' => $value["middle_name"],
                    'last_name' => $value["last_name"],
                    'suffix' => $value["suffix"],
                    'gender' => $value["gender"],
                    'birthdate' => $value["birthdate"],
                    'mobile_number' => $value["mobile_number"],
                    'telephone_number' => $value["telephone_number"],
                    'email' => $value["email"],
                    'address' => $value["address"],
                    'job_id' => $job->id,
                ]);
            }
        }
    }
}
